# Generated by Django 3.0.5 on 2021-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_notice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
