# Generated by Django 3.0.5 on 2021-10-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20211015_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
