# Generated by Django 3.0.5 on 2021-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20211015_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
