# Generated by Django 3.0.5 on 2021-10-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20211024_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='Your Name', max_length=30, null=True)),
                ('student_first_name', models.CharField(default='None', max_length=30, null=True)),
                ('student_last_name', models.CharField(default='None', max_length=30, null=True)),
                ('roll', models.CharField(max_length=10)),
                ('course_unit', models.CharField(max_length=10)),
                ('assignments', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Tests', models.DecimalField(decimal_places=1, max_digits=3)),
                ('exam', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
