# Generated by Django 3.0.5 on 2021-10-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_grading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='student_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grading',
            name='student_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
