# Generated by Django 3.0.5 on 2021-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20211030_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='total',
            field=models.DecimalField(decimal_places=1, default='0.0', max_digits=3),
        ),
    ]
