# Generated by Django 3.0.5 on 2021-10-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20211030_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='total',
            field=models.DecimalField(decimal_places=1, default='0.0', max_digits=6),
        ),
    ]
