# Generated by Django 4.0.3 on 2022-09-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('starting_time', models.CharField(max_length=100)),
                ('ending_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('a', models.CharField(max_length=5)),
                ('b', models.CharField(max_length=5)),
                ('c', models.CharField(max_length=5)),
                ('d', models.CharField(max_length=5)),
                ('answer', models.CharField(max_length=5)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.test')),
            ],
        ),
    ]
