# Generated by Django 4.0.3 on 2022-09-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_test_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='ending_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='starting_time',
            field=models.DateTimeField(),
        ),
    ]
