# Generated by Django 4.0.3 on 2022-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='answer',
            name='mark',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='student_username',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='a',
            field=models.TextField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='b',
            field=models.TextField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.TextField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.TextField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
